// Code generated by protoc-gen-go. DO NOT EDIT.
// source: im.proto

package im

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageAction int32

const (
	MessageAction_Unknown  MessageAction = 0
	MessageAction_Text     MessageAction = 1
	MessageAction_Image    MessageAction = 2
	MessageAction_Sound    MessageAction = 3
	MessageAction_Video    MessageAction = 4
	MessageAction_Face     MessageAction = 5
	MessageAction_Location MessageAction = 6
	MessageAction_File     MessageAction = 7
	MessageAction_Gift     MessageAction = 8
	//    Notify = 9; //通知
	MessageAction_Push MessageAction = 10
)

var MessageAction_name = map[int32]string{
	0:  "Unknown",
	1:  "Text",
	2:  "Image",
	3:  "Sound",
	4:  "Video",
	5:  "Face",
	6:  "Location",
	7:  "File",
	8:  "Gift",
	10: "Push",
}

var MessageAction_value = map[string]int32{
	"Unknown":  0,
	"Text":     1,
	"Image":    2,
	"Sound":    3,
	"Video":    4,
	"Face":     5,
	"Location": 6,
	"File":     7,
	"Gift":     8,
	"Push":     10,
}

func (x MessageAction) String() string {
	return proto.EnumName(MessageAction_name, int32(x))
}

func (MessageAction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_36f2114a3e4ddb9e, []int{0}
}

//发送消息
type SendMsgReq struct {
	Seq int64 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	//消息类型  1-单聊 2-群聊 3-聊天室
	//群聊跟聊天室的区别  群聊可以加入多个，且不在线情况下仍可收到消息  聊天室只能加入一个，且如果不在线则收不到消息
	Type                 int32         `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Action               MessageAction `protobuf:"varint,3,opt,name=action,proto3,enum=im.MessageAction" json:"action,omitempty"`
	From                 int64         `protobuf:"varint,4,opt,name=from,proto3" json:"from,omitempty"`
	To                   int64         `protobuf:"varint,5,opt,name=to,proto3" json:"to,omitempty"`
	Content              string        `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SendMsgReq) Reset()         { *m = SendMsgReq{} }
func (m *SendMsgReq) String() string { return proto.CompactTextString(m) }
func (*SendMsgReq) ProtoMessage()    {}
func (*SendMsgReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_36f2114a3e4ddb9e, []int{0}
}

func (m *SendMsgReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMsgReq.Unmarshal(m, b)
}
func (m *SendMsgReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMsgReq.Marshal(b, m, deterministic)
}
func (m *SendMsgReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMsgReq.Merge(m, src)
}
func (m *SendMsgReq) XXX_Size() int {
	return xxx_messageInfo_SendMsgReq.Size(m)
}
func (m *SendMsgReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMsgReq.DiscardUnknown(m)
}

var xxx_messageInfo_SendMsgReq proto.InternalMessageInfo

func (m *SendMsgReq) GetSeq() int64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *SendMsgReq) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *SendMsgReq) GetAction() MessageAction {
	if m != nil {
		return m.Action
	}
	return MessageAction_Unknown
}

func (m *SendMsgReq) GetFrom() int64 {
	if m != nil {
		return m.From
	}
	return 0
}

func (m *SendMsgReq) GetTo() int64 {
	if m != nil {
		return m.To
	}
	return 0
}

func (m *SendMsgReq) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type SendMsgResp struct {
	Seq                  int64    `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	MsgId                int64    `protobuf:"varint,2,opt,name=msgId,proto3" json:"msgId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMsgResp) Reset()         { *m = SendMsgResp{} }
func (m *SendMsgResp) String() string { return proto.CompactTextString(m) }
func (*SendMsgResp) ProtoMessage()    {}
func (*SendMsgResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_36f2114a3e4ddb9e, []int{1}
}

func (m *SendMsgResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMsgResp.Unmarshal(m, b)
}
func (m *SendMsgResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMsgResp.Marshal(b, m, deterministic)
}
func (m *SendMsgResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMsgResp.Merge(m, src)
}
func (m *SendMsgResp) XXX_Size() int {
	return xxx_messageInfo_SendMsgResp.Size(m)
}
func (m *SendMsgResp) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMsgResp.DiscardUnknown(m)
}

var xxx_messageInfo_SendMsgResp proto.InternalMessageInfo

func (m *SendMsgResp) GetSeq() int64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *SendMsgResp) GetMsgId() int64 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

type Nil struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Nil) Reset()         { *m = Nil{} }
func (m *Nil) String() string { return proto.CompactTextString(m) }
func (*Nil) ProtoMessage()    {}
func (*Nil) Descriptor() ([]byte, []int) {
	return fileDescriptor_36f2114a3e4ddb9e, []int{2}
}

func (m *Nil) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Nil.Unmarshal(m, b)
}
func (m *Nil) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Nil.Marshal(b, m, deterministic)
}
func (m *Nil) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Nil.Merge(m, src)
}
func (m *Nil) XXX_Size() int {
	return xxx_messageInfo_Nil.Size(m)
}
func (m *Nil) XXX_DiscardUnknown() {
	xxx_messageInfo_Nil.DiscardUnknown(m)
}

var xxx_messageInfo_Nil proto.InternalMessageInfo

type AuthReq struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Uid                  int64    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Uuid                 int64    `protobuf:"varint,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
	SdkVersion           string   `protobuf:"bytes,4,opt,name=sdkVersion,proto3" json:"sdkVersion,omitempty"`
	DeviceId             string   `protobuf:"bytes,5,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	Platform             string   `protobuf:"bytes,6,opt,name=platform,proto3" json:"platform,omitempty"`
	Model                string   `protobuf:"bytes,7,opt,name=model,proto3" json:"model,omitempty"`
	System               string   `protobuf:"bytes,8,opt,name=system,proto3" json:"system,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthReq) Reset()         { *m = AuthReq{} }
func (m *AuthReq) String() string { return proto.CompactTextString(m) }
func (*AuthReq) ProtoMessage()    {}
func (*AuthReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_36f2114a3e4ddb9e, []int{3}
}

func (m *AuthReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthReq.Unmarshal(m, b)
}
func (m *AuthReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthReq.Marshal(b, m, deterministic)
}
func (m *AuthReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthReq.Merge(m, src)
}
func (m *AuthReq) XXX_Size() int {
	return xxx_messageInfo_AuthReq.Size(m)
}
func (m *AuthReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthReq.DiscardUnknown(m)
}

var xxx_messageInfo_AuthReq proto.InternalMessageInfo

func (m *AuthReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AuthReq) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *AuthReq) GetUuid() int64 {
	if m != nil {
		return m.Uuid
	}
	return 0
}

func (m *AuthReq) GetSdkVersion() string {
	if m != nil {
		return m.SdkVersion
	}
	return ""
}

func (m *AuthReq) GetDeviceId() string {
	if m != nil {
		return m.DeviceId
	}
	return ""
}

func (m *AuthReq) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *AuthReq) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *AuthReq) GetSystem() string {
	if m != nil {
		return m.System
	}
	return ""
}

func init() {
	proto.RegisterEnum("im.MessageAction", MessageAction_name, MessageAction_value)
	proto.RegisterType((*SendMsgReq)(nil), "im.SendMsgReq")
	proto.RegisterType((*SendMsgResp)(nil), "im.SendMsgResp")
	proto.RegisterType((*Nil)(nil), "im.Nil")
	proto.RegisterType((*AuthReq)(nil), "im.AuthReq")
}

func init() { proto.RegisterFile("im.proto", fileDescriptor_36f2114a3e4ddb9e) }

var fileDescriptor_36f2114a3e4ddb9e = []byte{
	// 428 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0x25, 0xdf, 0xe9, 0x14, 0x8a, 0x19, 0x21, 0x64, 0x55, 0x08, 0x55, 0x3d, 0x95, 0x3d, 0xf4,
	0xb0, 0x88, 0x1f, 0xb0, 0x17, 0x50, 0x25, 0x76, 0xb5, 0xca, 0xc2, 0xde, 0x43, 0xe2, 0xa6, 0x56,
	0x63, 0x3b, 0x5b, 0x3b, 0xc0, 0x1e, 0xf8, 0x25, 0xfc, 0x24, 0xfe, 0x14, 0x1a, 0x27, 0x2d, 0x54,
	0xe2, 0xf6, 0xde, 0x9b, 0x99, 0xa7, 0x37, 0x1e, 0x43, 0x2e, 0xd5, 0xba, 0x3b, 0x18, 0x67, 0x30,
	0x94, 0x6a, 0xf9, 0x2b, 0x00, 0xb8, 0x13, 0xba, 0xbe, 0xb6, 0x4d, 0x21, 0x1e, 0x90, 0x41, 0x64,
	0xc5, 0x03, 0x0f, 0x16, 0xc1, 0x2a, 0x2a, 0x08, 0x22, 0x42, 0xec, 0x1e, 0x3b, 0xc1, 0xc3, 0x45,
	0xb0, 0x4a, 0x0a, 0x8f, 0xf1, 0x2d, 0xa4, 0x65, 0xe5, 0xa4, 0xd1, 0x3c, 0x5a, 0x04, 0xab, 0xd9,
	0xe5, 0x8b, 0xb5, 0x54, 0xeb, 0x6b, 0x61, 0x6d, 0xd9, 0x88, 0x2b, 0x5f, 0x28, 0xc6, 0x06, 0x1a,
	0xdf, 0x1e, 0x8c, 0xe2, 0xb1, 0x77, 0xf4, 0x18, 0x67, 0x10, 0x3a, 0xc3, 0x13, 0xaf, 0x84, 0xce,
	0x20, 0x87, 0xac, 0x32, 0xda, 0x09, 0xed, 0x78, 0xba, 0x08, 0x56, 0x93, 0xe2, 0x48, 0x97, 0xef,
	0x61, 0x7a, 0x0a, 0x67, 0xbb, 0xff, 0xa4, 0x7b, 0x09, 0x89, 0xb2, 0xcd, 0xa6, 0xf6, 0xf1, 0xa2,
	0x62, 0x20, 0xcb, 0x04, 0xa2, 0x1b, 0xd9, 0x2e, 0x7f, 0x07, 0x90, 0x5d, 0xf5, 0x6e, 0x57, 0x0c,
	0x8d, 0xce, 0xec, 0x85, 0xf6, 0xc3, 0x93, 0x62, 0x20, 0x64, 0xd8, 0xcb, 0xe3, 0x30, 0x41, 0xca,
	0xdb, 0x93, 0x14, 0x0d, 0x79, 0x09, 0xe3, 0x1b, 0x00, 0x5b, 0xef, 0xef, 0xc5, 0xc1, 0xd2, 0xca,
	0xb1, 0x37, 0xf8, 0x47, 0xc1, 0x39, 0xe4, 0xb5, 0xf8, 0x26, 0x2b, 0xb1, 0xa9, 0xfd, 0x56, 0x93,
	0xe2, 0xc4, 0xa9, 0xd6, 0xb5, 0xa5, 0xdb, 0x9a, 0x83, 0x1a, 0x97, 0x3b, 0x71, 0x1f, 0xde, 0xd4,
	0xa2, 0xe5, 0xd9, 0x90, 0xc9, 0x13, 0x7c, 0x05, 0xa9, 0x7d, 0xb4, 0x4e, 0x28, 0x9e, 0x7b, 0x79,
	0x64, 0x17, 0x3f, 0xe1, 0xd9, 0xd9, 0x13, 0xe3, 0x14, 0xb2, 0x2f, 0x7a, 0xaf, 0xcd, 0x77, 0xcd,
	0x9e, 0x60, 0x0e, 0xf1, 0x67, 0xf1, 0xc3, 0xb1, 0x00, 0x27, 0x90, 0x6c, 0x54, 0xd9, 0x08, 0x16,
	0x12, 0xbc, 0x33, 0xbd, 0xae, 0x59, 0x44, 0xf0, 0x5e, 0xd6, 0xc2, 0xb0, 0x98, 0x5a, 0x3f, 0x94,
	0x95, 0x60, 0x09, 0x3e, 0x85, 0xfc, 0x93, 0xa9, 0x4a, 0x72, 0x63, 0xa9, 0xd7, 0x65, 0x2b, 0x58,
	0x46, 0xe8, 0xa3, 0xdc, 0x3a, 0x96, 0x13, 0xba, 0xed, 0xed, 0x8e, 0xc1, 0xe5, 0x0e, 0xc2, 0x8d,
	0x42, 0x0e, 0xf1, 0xad, 0xd4, 0x0d, 0x66, 0x74, 0xf1, 0x1b, 0xd9, 0xce, 0x8f, 0x00, 0x2f, 0x20,
	0x1b, 0x4f, 0x85, 0x33, 0xd2, 0xfe, 0x7e, 0xaa, 0xf9, 0xf3, 0x33, 0x6e, 0x3b, 0x7c, 0x0d, 0x31,
	0xdd, 0x05, 0xa7, 0x54, 0x18, 0x2f, 0x74, 0x72, 0xfa, 0x9a, 0xfa, 0xdf, 0xf9, 0xee, 0x4f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xe6, 0xb0, 0x98, 0x60, 0xa9, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ImClient is the client API for Im service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ImClient interface {
	Ping(ctx context.Context, in *Nil, opts ...grpc.CallOption) (*Nil, error)
	SendMsg(ctx context.Context, in *SendMsgReq, opts ...grpc.CallOption) (*SendMsgResp, error)
	Auth(ctx context.Context, in *AuthReq, opts ...grpc.CallOption) (*Nil, error)
}

type imClient struct {
	cc *grpc.ClientConn
}

func NewImClient(cc *grpc.ClientConn) ImClient {
	return &imClient{cc}
}

func (c *imClient) Ping(ctx context.Context, in *Nil, opts ...grpc.CallOption) (*Nil, error) {
	out := new(Nil)
	err := c.cc.Invoke(ctx, "/im.Im/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imClient) SendMsg(ctx context.Context, in *SendMsgReq, opts ...grpc.CallOption) (*SendMsgResp, error) {
	out := new(SendMsgResp)
	err := c.cc.Invoke(ctx, "/im.Im/SendMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imClient) Auth(ctx context.Context, in *AuthReq, opts ...grpc.CallOption) (*Nil, error) {
	out := new(Nil)
	err := c.cc.Invoke(ctx, "/im.Im/Auth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ImServer is the server API for Im service.
type ImServer interface {
	Ping(context.Context, *Nil) (*Nil, error)
	SendMsg(context.Context, *SendMsgReq) (*SendMsgResp, error)
	Auth(context.Context, *AuthReq) (*Nil, error)
}

// UnimplementedImServer can be embedded to have forward compatible implementations.
type UnimplementedImServer struct {
}

func (*UnimplementedImServer) Ping(ctx context.Context, req *Nil) (*Nil, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedImServer) SendMsg(ctx context.Context, req *SendMsgReq) (*SendMsgResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMsg not implemented")
}
func (*UnimplementedImServer) Auth(ctx context.Context, req *AuthReq) (*Nil, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Auth not implemented")
}

func RegisterImServer(s *grpc.Server, srv ImServer) {
	s.RegisterService(&_Im_serviceDesc, srv)
}

func _Im_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Nil)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/im.Im/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImServer).Ping(ctx, req.(*Nil))
	}
	return interceptor(ctx, in, info, handler)
}

func _Im_SendMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMsgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImServer).SendMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/im.Im/SendMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImServer).SendMsg(ctx, req.(*SendMsgReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Im_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/im.Im/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImServer).Auth(ctx, req.(*AuthReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Im_serviceDesc = grpc.ServiceDesc{
	ServiceName: "im.Im",
	HandlerType: (*ImServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Im_Ping_Handler,
		},
		{
			MethodName: "SendMsg",
			Handler:    _Im_SendMsg_Handler,
		},
		{
			MethodName: "Auth",
			Handler:    _Im_Auth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "im.proto",
}
